"""Portable deterministic methods exports and non-mutating freshness checks."""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from .model import MathematicalPositioning, PositioningError
from .visualization import build_visual_model
from .visualization import projection_bytes as visual_projection_bytes


def _cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(model: Mapping[str, Any]) -> str:
    """Project all family axes and every canonical review without truncating assumptions."""
    counts = model["counts"]
    lines = [
        "# Mathematical positioning of FEP Formal",
        "",
        "Generated by `fep_lean.methods` from validated owner bytes and authored positioning policy.",
        "",
        model["evidence_boundary"],
        "",
        f"Package version: `{model['package_version']}`.",
        "",
        f"Source origin: `{model['source_origin']}`. Source hashes describe the bytes read for this analysis.",
        "",
        (
            f"The projection contains {counts['topics']} topics, {counts['families']} families, "
            f"{counts['domains']} overlapping domains, and {counts['authored_edges']} authored relations."
        ),
        "",
        "## Family coordinates",
        "",
        (
            "The classifications summarize reviewed invariants and carrier assumptions. "
            "A family domain is a union of its rows' concerns; each topic's exact scope follows below. "
            "Topic domain lists explicitly carry `inherited_family_context`, an editorial label rather than a semantic certification."
        ),
        "",
        "| Family | Topics | Mathematical domains |",
        "| --- | ---: | --- |",
    ]
    for family in model["family_positions"]:
        number = sum(topic["family"] == family["family"] for topic in model["topics"])
        lines.append(
            f"| {_cell(family['family'])} | {number} | {_cell(', '.join(family['domains']))} |"
        )
    for family in model["family_positions"]:
        lines.extend(
            [
                "",
                f"### {family['family']}",
                "",
                f"Carriers: {'; '.join(family['carriers'])}.",
                "",
                f"Scale: {'; '.join(family['scale'])}.",
            ]
        )
        for field, label in (
            ("topology", "Topology"),
            ("embedding", "Embedding"),
            ("statistics", "Statistics"),
            ("limits", "Boundary"),
        ):
            lines.extend(["", f"{label}: {family[field]}"])
    lines.extend(
        [
            "",
            "## Continuous native scope beyond catalogue families",
            "",
            (
                "These selected authored scope notes concern manifested source modules. "
                "The complete inventory is in the JSON projection. Listing a declaration "
                "here does not validate a native receipt or close its scientific acceptance gates."
            ),
        ]
    )
    cross = model.get("cross_corpus_embedding")
    if cross:
        lines.extend(
            [
                "",
                "## Common FEP / OpenAI mathematical coordinates",
                "",
                cross["assignment_boundary"],
                "",
                cross["coordinate_weight"],
                "",
                cross["relation_boundary"],
                "",
                "```json",
                json.dumps(
                    cross["projection"],
                    ensure_ascii=False,
                    sort_keys=True,
                    indent=2,
                    allow_nan=False,
                ),
                "```",
                "",
                "| Coordinate | Kind | Definition |",
                "| --- | --- | --- |",
            ]
        )
        lines.extend(
            f"| {_cell(row['id'])} | {_cell(row['axis_kind'])} | {_cell(row['definition'])} |"
            for row in cross["coordinates"]
        )
        lines.extend(
            ["", "| Record | Kind | Features | Scope |", "| --- | --- | --- | --- |"]
        )
        lines.extend(
            f"| {_cell(row['id'])} | {_cell(row['kind'])} | {_cell(', '.join(row['features']))} | {_cell(row['scope'])} |"
            for row in cross["rows"]
        )
        for row in cross["rows"]:
            if row["kind"] == "upstream_result":
                lines.extend(
                    [
                        "",
                        f"### {row['id']}: {row['title']}",
                        "",
                        f"Pinned statement source: [{row['source_path']}]({row['source_url']}); SHA-256 `{row['source_sha256']}`. Status: `{row['status']}`.",
                        "",
                        row["statement"],
                        "",
                        "Carriers: " + "; ".join(row["carriers"]),
                        "",
                        "Hypotheses/context: " + "; ".join(row["hypotheses"]),
                        "",
                        "Scope: " + row["scope"],
                        "",
                        "Assignment rationale: " + row["rationale"],
                    ]
                )
    for scope in model["continuous_scope"]:
        lines.extend(
            ["", f"### `{scope['resource']}`", "", scope["carrier"], "", scope["scope"]]
        )
    lines.extend(
        [
            "",
            "## Explicit feature space",
            "",
            model["feature_embedding"]["interpretation"],
            "",
            (
                "Each family is a binary vector in the ordered domain vocabulary. "
                "Similarity is shared domains divided by union domains, with equal weights. "
                "The candidates below are separate from all authored theorem relations."
            ),
            "",
            "| Family | First comparison candidate | Shared / union |",
            "| --- | --- | --- |",
        ]
    )
    for family in model["feature_embedding"]["row_order"]:
        candidates = model["retrieval_candidates"][family]
        first = candidates[0]
        lines.append(
            f"| {family} | {first['family']} | {first['shared_domains']} / {first['union_domains']} |"
        )
    lines.extend(["", "## Numerical boundary probes", ""])
    for probe in model["numerical_probes"]:
        lines.extend(
            [
                f"### {probe['id']}",
                "",
                "```json",
                json.dumps(
                    probe, ensure_ascii=False, indent=2, sort_keys=True, allow_nan=False
                ),
                "```",
                "",
            ]
        )
    lines.extend(
        [
            "## Exact topic review projection",
            "",
            (
                "Invariants, assumptions, non-vacuity, acceptance probes, and dispositions "
                "are copied from the maintained semantic review. The acceptance-probe text "
                "describes its canonical requirement; this module does not run it."
            ),
        ]
    )
    for topic in model["topics"]:
        review = topic["semantic_review"]
        lines.extend(
            [
                "",
                f"### {topic['id']}: {topic['title']}",
                "",
                f"Family: `{topic['family']}`. Disposition: `{review['disposition']}`.",
                "",
                f"Primary theorem: `{topic['primary_theorem_qualified']}`.",
                "",
                f"Body owner: `{topic['body_source']}`; canonical namespace `{topic['canonical_namespace']}`.",
            ]
        )
        for field, label in (
            ("invariant", "Invariant"),
            ("assumption_review", "Assumptions"),
            ("non_vacuity", "Non-vacuity"),
            ("acceptance_probe", "Canonical acceptance probe"),
        ):
            lines.extend(["", f"{label}: {review[field]}"])
        analysis = model.get("theorem_analysis")
        if analysis:
            primary = analysis["declarations"][topic["primary_theorem_qualified"]]
            context = primary["namespace_variable_context"]
            context_lines = (
                ["```lean", "\n".join(context), "```"] if context else ["none declared"]
            )
            lines.extend(
                [
                    "",
                    analysis["analysis_boundary"],
                    "",
                    "Exact primary Lean statement:",
                    "",
                    "```lean",
                    primary["statement"],
                    "```",
                    "",
                    "Namespace variable context:",
                    "",
                    *context_lines,
                    "",
                    "Exact typed binder groups (syntactic roles):",
                    "",
                    "```json",
                    json.dumps(
                        primary["binders"], ensure_ascii=False, sort_keys=True, indent=2
                    ),
                    "```",
                    "",
                    "Exact conclusion:",
                    "",
                    "```lean",
                    primary["conclusion"],
                    "```",
                    "",
                    f"Statement SHA-256: `{primary['statement_sha256']}`. Lexical declaration mentions are retained in the JSON; they do not certify kernel dependencies.",
                ]
            )
        for field, label in (
            ("supporting_theorems", "Supporting"),
            ("boundary_theorems", "Boundary"),
        ):
            refs = topic["reviewed_theorems_qualified"][field]
            lines.extend(
                [
                    "",
                    f"{label} theorems: "
                    + (
                        ", ".join(f"`{ref}`" for ref in refs)
                        if refs
                        else "none recorded"
                    )
                    + ".",
                ]
            )
    lines.extend(
        [
            "",
            "## Authored relations",
            "",
            (
                "Every edge is retained in authored order and with its original kind, rationale, "
                "and witness. `formal` and `formal_pairing` remain distinct; a conceptual edge "
                "does not gain a witness through this taxonomy. Capabilities and evidence "
                "lists are preserved completely in JSON."
            ),
            "",
        ]
    )
    for edge in model["authored_relations"]["edges"]:
        lines.extend(
            [
                f"- `{edge['source']}` → `{edge['target']}` ({edge['kind']}): {edge['rationale']}"
                + (f" Witness: `{edge['witness']}`." if "witness" in edge else ""),
                "",
            ]
        )
    lines.extend(
        [
            "## Source snapshots",
            "",
            (
                "SHA-256 values bind the bytes read for this informational projection. "
                "They are not a native receipt or continuous consumption-custody assertion."
            ),
            "",
            "| Source | SHA-256 |",
            "| --- | --- |",
        ]
    )
    lines.extend(
        f"| `{path}` | `{digest}` |" for path, digest in model["source_sha256"].items()
    )
    return "\n".join(lines) + "\n"


def mathematical_positioning_bytes(model: MathematicalPositioning) -> dict[Path, bytes]:
    """Render all contracts, the interactive offline map, and publication SVG panels."""
    data = model.as_dict()
    visual = build_visual_model(data)
    products = visual_projection_bytes(visual)
    products[Path("positioning.json")] = (
        json.dumps(data, ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False)
        + "\n"
    ).encode()
    products[Path("positioning.md")] = render_markdown(data).encode()
    for path in products:
        if path.is_absolute() or ".." in path.parts:
            raise PositioningError("methods renderer produced an unsafe relative path")
    return products


def export_mathematical_positioning(
    model: MathematicalPositioning, output_root: Path
) -> tuple[Path, ...]:
    """Write only the selected output tree, atomically per complete rendered artifact."""
    from fep_lean.output.fsutil import atomic_write_bytes

    products = mathematical_positioning_bytes(model)
    paths = []
    for relative, content in products.items():
        destination = Path(output_root) / relative
        atomic_write_bytes(destination, content)
        paths.append(destination)
    return tuple(paths)


def mathematical_positioning_drift(
    model: MathematicalPositioning, output_root: Path
) -> tuple[Path, ...]:
    """Compare exact artifact bytes without writing or creating an output directory."""
    return tuple(
        Path(output_root) / relative
        for relative, content in mathematical_positioning_bytes(model).items()
        if not (Path(output_root) / relative).is_file()
        or (Path(output_root) / relative).read_bytes() != content
    )
